const relatedActivities = {
    hiking: [
        'Hiking',
        'Front-Country Hiking',
        'Backcountry Hiking',
        'Off-Trail Permitted Hiking',
    ],
    camping: [
        'Camping',
        'Backcountry Camping',
        'Car or Front Country Camping',
        'Canoe or Kayak Camping',
        'Horse Camping (see also Horse/Stock Use)',
    ],
    boating: ['Boating', 'Boat Tour', 'Kayaking', 'Canoe or Kayak Camping'],
    skiingAndSnowSports: [
        'Skiing',
        'Cross-Country Skiing',
        'Downhill Skiing',
        'Snowshoeing',
        'Snowmobiling',
        'Snow Play',
    ],
    biking: ['Biking', 'Mountain Biking', 'Road Biking'],
    climbing: [
        'Rock Climbing',
        'Mountain Climbing',
        'Climbing',
        'Canyoneering',
    ],
    toursAndGuided: [
        'Guided Tours',
        'Self-Guided Tours - Walking',
        'Self-Guided Tours - Auto',
        'Bus/Shuttle Guided Tour',
    ],
    wildlifeAndNature: [
        'Wildlife Watching',
        'Birdwatching',
        'Stargazing',
        'Astronomy',
    ],
    fishing: ['Fishing', 'Saltwater Fishing', 'Freshwater Fishing'],
    culturalAndEducational: [
        'Museum Exhibits',
        'Arts and Culture',
        'Cultural Demonstrations',
        'First Person Interpretation',
        'Junior Ranger Program',
    ],
    shoppingAndFood: [
        'Bookstore and Park Store',
        'Gift Shop and Souvenirs',
        'Food',
        'Shopping',
    ],
    horseActivities: [
        'Horseback Riding',
        'Horse Camping (see also Horse/Stock Use)',
        'Horse Trekking',
    ],
    waterActivities: [
        'Swimming',
        'Freshwater Swimming',
        'Snorkeling',
        'Surfing',
    ],
    offRoadAndDriving: ['Scenic Driving', 'Auto and ATV', 'Auto Off-Roading'],
    otherActivities: [
        'Playground',
        'Hands-On',
        'Geocaching',
        'Gathering and Foraging',
        'Hunting',
        'Flying',
        'Fixed Wing Flying',
    ],
};

module.exports = relatedActivities;
